<?php
$clang['ban'] = '%hunter% banladı. Banlanan %target%';
$clang['unban'] = '%hunter% banını kaldırdı. Engel kalkan %target%';
$clang['room_block'] = '%hunter% blok yaptı. Bloklanan %target%  %room% kanalında';
$clang['room_unblock'] = '%hunter% bloku kaldırdı. Engeli kaldırılan %target%  %room% kanalında';
$clang['mute'] = '%hunter% susturdu. Susturulan %target%   %delay% süre ile';
$clang['unmute'] = '%hunter% susturma kaldırdı. Engeli kaldırılan %target% ';
$clang['room_mute'] = '%hunter% susturdu. Susturulan %target%  %room% kanalında';
$clang['room_unmute'] = '%hunter% susturma kaldırdı. Engeli kalkan %target%  %room% kanalında';
$clang['spam_mute'] = '%hunter% susturma yaptı. Susturulan %target%  %delay% süre ile neden spam';
$clang['spam_ban'] = '%hunter% ban yaptı. Banlanan %target% neden spam';
$clang['flood_mute'] = '%hunter% susturma yaptı. Susturulan %target% %delay% süre ile neden flood';
$clang['word_mute'] = '%hunter% susturma yaptı. Susturulan %target% %delay% süre ile neden kötü dil';
$clang['word_kick'] = '%hunter% tekmele yaptı. telkmelenen %target% %delay% süre ile neden kötü dil';
$clang['verify_account'] = '%hunter% Doğrulama yaptı. Doğrulanan Kullanıcı %target%';
$clang['clear_logs'] = '%hunter% Kanal geçmişini temizledi. Temizlenen kanal %room%';
$clang['change_name'] = '%oldname% ismini değiştiridi. Yeni ismi %hunter%';
$clang['rename_user'] = '%hunter% has renamed %data% to %target%';
$clang['change_rank'] = '%hunter% yetki değiştirdi. Yetkisi değişen %target% yeni seviyesi %rank%';
$clang['change_topic'] = '%hunter% Kanal başlığını  %room% kanalından değiştirdi';
$clang['delete_room'] = '%hunter% odayı sildi %data%';
$clang['create_room'] = '%hunter% oda oluşturdu %room%';
$clang['delete_account'] = '%hunter% hesap sildi. Silinen  %data% hesap';
$clang['addons_install'] = '%hunter% Yeni bir modül kurdu. Kurulan modül %data%';
$clang['addons_uninstall'] = '%hunter% modül sildi. Silinen modül %data%';
$clang['remove_avatar'] = '%hunter% , %target% profil resmini sildi';
$clang['change_avatar'] = '%hunter% , %target% profil resmini değiştirdi';
$clang['change_room_rank'] = '%hunter% , %target% oda yetkisini %roomrank% olarak değiştirdi %room%';
$clang['change_color'] = '%hunter% , %target% rengini değiştirdi';
$clang['edit_profile'] = '%hunter% , %target% profilini değiştirdi';
$clang['create_user'] = '%hunter% , %target% kullanıcısını oluşturdu';
$clang['clear_console'] = '%hunter% konsolu temizledi';
$clang['kick'] = '%hunter%,%target% tekmeledi neden= %delay%';
$clang['unkick'] = '%hunter%, %target% tekme yasağını kaldırdı';
$clang['mood_user'] = '%hunter% , %target% ruh halini düzenledi';
$clang['pass_user'] = '%hunter% , %target% şifresini değiştirdi';
$clang['change_cover'] = '%hunter% ,%target% arka paln resmini değiştirdi';
$clang['remove_cover'] = '%hunter% ,%target% arkapaln resmini sildi';
$clang['change_verify'] = '%hunter% , %target% doğrulamasını değiştirdi';
$clang['wall_delete'] = '%hunter% Arkadaş duvarından bir  gönderisini sildi %target%';
$clang['news_delete'] = '%hunter% Haber duvarından bir haber sildi %target%';
$clang['cwall_delete'] = '%hunter% Arkadaş duvarından bir yorumu sildi %target%';
$clang['cnews_delete'] = '%hunter% Haber duvarından bir haber sildi %target%';
$clang['delete_log'] = '%hunter% Silindi %target% oturum aç %room%';


$clang['flood_kick'] = '%hunter% has kicked %target% for %delay% for flooding';
$clang['vpn_kick'] = '%hunter% has kicked %target% for %delay% for using VPN or proxy';
$clang['main_mute'] = '%hunter% has main muted %target% for %delay%';
$clang['main_unmute'] = '%hunter% has removed %target%\'s main mute';
$clang['private_mute'] = '%hunter% has private muted %target% for %delay%';
$clang['private_unmute'] = '%hunter% has removed %target%\'s private mute';
$clang['ghost'] = '%hunter% has ghosted %target% for %delay%';
$clang['unghost'] = '%hunter% has unghosted %target%';
$clang['room_block'] = '%hunter% has blocked %target% in %room% room for %delay%';
$clang['room_mute'] = '%hunter% has muted %target% in %room% room for %delay%';
$clang['vpn_change'] = '%hunter% has changed %target%\'s  VPN setting';
$clang['add_note'] = '%hunter% has added a note to %target%';
$clang['gold_share'] = '%hunter% has shared %data% gold with %target%';
$clang['self_delete'] = '%hunter% has requested their account to be deleted';

?>